### ISSUE TITLE
Body copy line height

### ISSUE THREAD

**Issue by rileyflorence** [fs-webdev/fs-styles#21]
I'd love to have the body copy line height changed to 20px, not the 22px. The current line height is a bit much for the data density we require in Search.

**Comment by lambertsteven** [comment]
What would you like the line heights to change to?

**Comment by rileyflorence** [comment]
16/20 and 14/18 is what I think we should do.

**Comment by swordboy1** [comment]
I like those line heights. What do you think, @flpetho ?
