### ISSUE TITLE
Color rgb Values

### ISSUE THREAD

**Issue by rileyflorence** [fs-webdev/fs-styles#23]
Can we get the rgb Values added for the colors? I find myself creating them so I can use opacity.

**Comment by lambertsteven** [comment]
I can add that soon. I'll let you know when it's done.

**Comment by rileyflorence** [comment]
Awesome. If it helps, here the colors are in order:
Full Color Logo:
Green: 135, 185, 64
Grey: 186, 183, 177
Tan: 156, 148, 122

Single Color
Green: 135, 185, 64
Black: 0, 0, 0
White: 255, 255, 255

Accent Colors:
Red: 241, 100, 88
Blue: 39, 196, 244
Orange: 252, 179, 75
Green: 191, 215, 48
Purple: 153, 103, 153
Tan: 156, 148, 122

Text
Body: 51, 51, 49
Header: 77, 77, 74
Label: 102, 102, 98

Gender
Male: 601, 143, 247
Female: 226, 63, 123
Unknown: 102, 102, 98

Light Gender
Male: 153, 196, 254
Female: 244, 142, 182

Horizontal Divider: 204, 204, 204

**Comment by lambertsteven** [comment]
Alright, rgb colors added.
