### ISSUE TITLE
Dual Blue Link Colors

### ISSUE THREAD

**Issue by mattspencer** [fs-webdev/fs-styles#24]
I've noticed that there are two link colors across the site #0051C4 and #0088CC

#0051C4 (Dark Blue in living style guide) Used in: Tree, Search, 1/2 of Homepage.
#0088CC (Default Bootstrap Blue) Used in: Memories, Indexing, Volunteer, Ask, Sign-In page, Get Help menu, 1/2 of Homepage.

#0051C4 passes contrast at 7.06 and #0088CC fails at 3.89.

To me the lighter blue feels more like the rest of our color pallet and the darker blue doesn't stand out very well in body copy. I am proposing using one color that meets in the middle. (For example taking our blue color swatch of #27C4F4 and then multiplying that color on itself 3 times gives you #0073DE which passes contrast.)

**Comment by swordboy1** [comment]
I agree that the lighter blue link color feels friendlier, more FamilySearchish. I prefer it, but it absolutely needs to be darkened a little to pass contrast accessibility standards.

**Comment by lambertsteven** [comment]
So what color should we use?

**Comment by lambertsteven** [comment]
[WebAim](http://webaim.org/techniques/hypertext/link_text#underlining) suggests that the link color (for non-underlined links) should have a contrast ratio of 3:1 to the surrounding body text. 

#0073DE has a contrast ratio of 2.72, so we would still need to lighten it up slightly to get a 3:1 ratio.

**Comment by lambertsteven** [comment]
@swordboy1 how do you feel about #0073DE?
![screen shot 2015-05-20 at 11 22 00 am](https://cloud.githubusercontent.com/assets/6578039/7732113/94b3a81a-fee2-11e4-8f56-e1f3eb95afb0.png)
![screen shot 2015-05-20 at 11 22 35 am](https://cloud.githubusercontent.com/assets/6578039/7732114/94b5a570-fee2-11e4-9add-f5f09ecf3f49.png)

**Comment by swordboy1** [comment]
@lambertsteven I like it. Does it better meet accessibility standards? Is that why you're suggesting it?

**Comment by lambertsteven** [comment]
I was just trying to see if this issue was still relevant. I do like the lighter blue color link, and it still passes contrast ratio. Matt was the first to suggest it.

**Comment by lambertsteven** [comment]
If we do change the light blue, we may want to do the same with the visited purple

**Comment by swordboy1** [comment]
I'm not sure I can make that call to make the switch. Maybe we should consult @flpetho

**Comment by swordboy1** [comment]
@lambertsteven we can close this issue, right? Didn't we implement the new link color in the latest style guide?

**Comment by lambertsteven** [comment]
We actually did, we modified the color to #0060d7. This has a contrast ratios of:

foreground | background | ratio
 -------------- | ---------------- | ------
0060d7 | ffffff | 5.75:1
0060d7 | e4e4e4 | 4.52:1
0060d7 | 333331 |  2.2:1
0060d7 | ecebea | 4.83:1

![image](https://cloud.githubusercontent.com/assets/6578039/8600115/657f6410-2621-11e5-8ac4-c581d7d157f6.png)

As you can see, the link color to text color is close to 3:1, but still a bit off.

However, I was thinking. What if we change the color to be the same as the button color #3073dd? This has two benefits. The first is that we don't introduce another color. The second is that it raises the text color contrast to as close to 3 as we can get, but it does reduce all other ratios a by a full point.

foreground | background | ratio
 -------------- | ---------------- | ------
3073dd | ffffff | 4.54:1
3073dd | e4e4e4 | 3.57:1
3073dd | 333331 |  2.79:1
3073dd | ecebea | 3.82:1

![image](https://cloud.githubusercontent.com/assets/6578039/8600125/81169446-2621-11e5-9c98-aeab739f532b.png)

Thoughts @mattspencer @flpetho @swordboy1?
