### ISSUE TITLE
Move the text color descriptions from the Acceptable Use to on top of the swatches

### ISSUE THREAD

**Issue by swordboy1** [fs-webdev/fs-styles#25]
@lambertsteven can we move the text color descriptions from the Acceptable Use area to be on top of the color swatches themselves? I think it would make it easier to understand and read. Here is what I'm hoping to see:
![screen shot 2015-01-07 at 4](https://cloud.githubusercontent.com/assets/8442852/5655485/e41347f4-968b-11e4-979e-227a5d0cc8ff.png)

**Comment by swordboy1** [comment]
Also, can we add swatches of the text link colors?

**Comment by lambertsteven** [comment]
Will do. Did you read issue #24? Should we change the link color?

**Comment by swordboy1** [comment]
Yes, I just commented on #24 . I'm not opposed to changing it.
