### ISSUE TITLE
Subnav Issue in Safari

### ISSUE THREAD

**Issue by swordboy1** [fs-webdev/fs-styles#29]
@lambertsteven there is a problem in how the new subnav looks in Safari.

![screen shot 2015-02-10 at 11 12 20 am](https://cloud.githubusercontent.com/assets/8442852/6133257/ec7c6476-b115-11e4-9de0-6ac8f9166df7.png)
![screen shot 2015-02-10 at 11 12 34 am](https://cloud.githubusercontent.com/assets/8442852/6133258/ec8d9548-b115-11e4-9bda-c28562951d5a.png)

**Comment by lambertsteven** [comment]
Ha, serves me right for not including vendor prefixes...
