### ISSUE TITLE
Search team retroactive implementation feedback

### ISSUE THREAD

**Issue by rileyflorence** [fs-webdev/fs-styles#32]
I sat down with Reuben Perry, Benjamin Limb, and Bobby Helco from the Search Team to capture some of their thoughts after having spent some time going back and implementing the style guide on existing pages. This is what they had to say:

**What went well**
* The documentation existing is a good thing. 
* The people that built it are available for questions.
* It's unifying our pages
* Amount of communication has been pretty good - people have been willing to help and open to discussion and suggestions

**What could have gone better**
* It's hard to automate - we can't detect the image variances
* Replacing the old code is hard because we have functional markup that isn't functional with the new style.
* We have functionality dependent on tag names that can break in the transition
* Sometimes it takes a complete tear-down and rebuild to make the new stuff work instead of an easy "swap."
* Documentation is lacking some important information. What should/can I use?
* Style guide had things removed after we implemented it, which broke (the footer?)
* If code ever gets removed "search" to see if it's being used, please. Lets put more thought into the removal of code please.
* An update/patch list. What was changed. What was added. Put this out with the announcement of the "next version"
* A way to see what is using the style guide.
* A list of who to talk to about what and how to implement it

**Thoughts Ideas**
* When "testing" strip out all of your own styles so you can see just the style guide without the chance of it being overwritten
* How do we address browser css? Can we remove that too?
* [Wraith](http://csste.st/tools/wraith.html) does an image comparison, it highlights in red the differences. Look in to this or something like it.
* One of the acceptance criteria when implementing this should be going through the page with the UX and reviewed changes and differences.

**QA Should look for**
* When implementing the style guide wipes out little hacks or bandaids. Using pixel padding instead of centering to get proper spacing. A rough example: We do a .search_app .details_header h3 { padding-left: 5px } but when we go to the style guide we lose that sneaky padding-left. Some of the little bandaids might have to move to their own classes.

**Comment by straker** [comment]
Sweet! Thanks for doing all this Riley.
