### ISSUE TITLE
Can we add common web components to the style guide?

### ISSUE THREAD

**Issue by swordboy1** [fs-webdev/fs-styles#33]
I think it would be useful to list commonly-used custom web components used by various apps on FamilySearch on the style guide. Such as the "report abuse" submit modal component, etc.

**Comment by lambertsteven** [comment]
I would love to see this as well. The only problem is that nothing we have on the site is a web component. Most of them are angular directives or not sharable. We're close to getting web components into prod, but they are about a month off from being fully supported.

I think the first web component will be the person card that all teams can use.

**Comment by lambertsteven** [comment]
Moving to fs-webdev/fs-styleguide#5
