### ISSUE TITLE
Adjusting value of colors

### ISSUE THREAD

**Issue by davepack** [fs-webdev/fs-styles#35]
Working with Riley we found the best way to adjust the value of colors without actually making backgrounds transparent is to use the 'lighten' function in stylus (documented here: https://learnboost.github.io/stylus/docs/bifs.html). For example, for purple (#996799), in some cases we are using 'rgba(191,215,48,.2)' to achieve a lighter shade, but this is also transparent. A better method would be to use 'lighten(#996799,80%)', which returns the actual hex value of the color lightened by 80% with 100% opacity (in this case #ebe1eb).

**Comment by lambertsteven** [comment]
Thanks @davepack. I'll add this information to the style guide in the accent colors section in the next build.
