### ISSUE TITLE
Modals should close by clicking outside of the modal

### ISSUE THREAD

**Issue by swordboy1** [fs-webdev/fs-styles#39]
I think that we should allow users to click anywhere outside of a modal to close the modal. It is a quick way to cancel without having to fish around for an "x" or cancel button. Plus, canceling a modal by clicking outside is a convention used on many popular sites that many our users are probably used to using: Facebook, Pinterest, Trello, Behance, etc. @intervalia @lambertsteven @flpetho

**Comment by intervalia** [comment]
There are 4 main types of dialogs:
**Modal**: Explicit action required to close and background is disabled.
**Non-modal**: Implicit action to close (Clicking on a button or off the dialog, as well as pressing the escape key) and background is NOT disabled.
**Call-out**: Like a non-modal but it includes the arrow to point at the item that brought the call-out up. Auto positions for best fit on screen.
**Drop-down**: Like a call-out but only positions down from the item that brought it up. 

The **modal** vs **non-modal** functionality described above is common for how dialogs work in most, if not all OSs.

**Comment by swordboy1** [comment]
All of the example sites I listed above appear to have dialogs that are Non-Modal yet they all disable the background. 

I don't think I've ever experienced a Modal on the web as you described it. I would love to see example cases for the use of Modals and Non-Modals because I think we only have Non-Modals on our site today.

**Comment by lambertsteven** [comment]
Looks like we need to do some investigating into how everyone uses modals at FS, just like we've done with buttons and alerts

**Comment by lambertsteven** [comment]
By default, normal conventions dictate that the modal should close when clicked outside the modal. In cases such as modal flows or where the user has to enter a lot of information, you may wish to prevent clicking outside the modal from closing it.
