### ISSUE TITLE
fs-modal and fs-person styles not loaded

### ISSUE THREAD

**Issue by robhicks** [fs-webdev/fs-styles#40]
I turned on fsStylesEx. After doing so, I noticed that some styles from the modules subfolder do not get loaded, name the styles in _persons.styl and _modal.styl. I noted that familysearch-styles.styl seems configured to load everything in the modules subfolder.  

The app I'm working does not have fs-styles, theme-engage or woodruff pinned.

**Comment by lambertsteven** [comment]
When you open familysearch-styles.css in the sources pannel, what's the version number in the comment at the top of the file?

**Comment by robhicks** [comment]
It's 1.5.0 and looking in the fs-styles folder under node_modules, all of the files in the 1.5.0 release of fs-styles are included.

**Comment by lambertsteven** [comment]
Do you have a page I can see? https://familysearch.org/apps/ loads the current version of fs-styles and I can use styles for modals and persons.

**Comment by robhicks** [comment]
@lambertsteven Yes, take a look at https://beta.familysearch.org/indexing/admin-new/templates/list. I just deployed it. If you don't have access, let me your username and I'll get you access. 

Note It now has fs-person styles but still not fs-modal styles.

**Comment by lambertsteven** [comment]
You're loading an old version of the styles. Are you using any dependencies that depend on fs-styles? There's a bug in asset manager when determining which file to use when there are multiple versions of the same file (when multiple repos depend on the same repo). This might be the problem.

**Comment by robhicks** [comment]
Okay. I was using fs-styles directly, importing it's main style file directly into my app style file. In trying to embrace fs-styles from theme-engage, I simply enabled the experiment and removed my direct fs-styles import. I take it from what you said, I need to remove it from package.json and allow theme-engage to load it. However, when I tried that, theme-enaged loaded v1.4.2 of fs-styles. This is after having removed and reinstalled theme-engage. In looking at the latest theme-engage package.json file, it appears that it is pinned at 1.4.2 of fs-styles. Given this, it seems I'm trying to jump the gun on using the fs-styles modals. Am I?

**Comment by lambertsteven** [comment]
No, the [latest master of theme-engage](https://github.com/fs-webdev/theme-engage/blob/4.6.14/package.json) (and since v4.6.14) is pinned to version 1.5.0 of fs-styles.

**Comment by robhicks** [comment]
Okay, i figured it out. My app is not pinned to a version of theme-engage but was using a fork. All is well again. Sorry for the confusion.

**Comment by lambertsteven** [comment]
np.
