### ISSUE TITLE
Add docs for `fs-modal--show`

### ISSUE THREAD

**Issue by robhicks** [fs-webdev/fs-styles#41]
@lambertsteven I integrated the latest fs-styles in the new indexing admin app. However, the modal looks small. Inspecting it in the browser all of the sizes look ok. Even removing all upstream styles for the app (not the ones inherited from theme-engage), it looks small. 
Do you mind taking a [look](https://beta.familysearch.org/indexing/admin-new)? 
You can activate the modal by selecting a template and clicking the trash can.
Thanks!

**Comment by lambertsteven** [comment]
Ah, I see the problem (and it's my fault for not creating the documentation for it). To open the modal, add the class `fs-modal--show` to the `fs-modal__overlay` div. The modal is scaled down to 70% of it's size and then scaled up to 100% when the `fs-modal--show` class is added to create a nice coming into the screen animation. I'll add the documentation in the next release.

**Comment by robhicks** [comment]
@lambertsteven Thanks! Works great!

**Comment by lambertsteven** [comment]
I'll leave this open until I get it added to the docs, just to keep a reminder that I need to do it.
