### ISSUE TITLE
fs-styles should include a pre-built CSS file

### ISSUE THREAD

**Issue by jshcrowthe** [fs-webdev/fs-styles#42]
At the moment it is a little awkward for any 3rd parties to consume the styleguide. (I saw a question from a while back [see: #8]). It is also difficult to consume the styleguide for use in webcomponents due to the use of stylus. 

If we could create a `dist` folder somewhere in the repo (doesn't really matter where) with a compilied, autoprefixed, minified version of the styles that'd simplify it's consumption outside of FamilySearch context significantly.

I'll throw together a gulp workflow that will do all this so that those who work on the styleguide need only have that gulp script running to keep an up to date `dist` folder.

**Comment by lambertsteven** [comment]
also related to #8
