### ISSUE TITLE
Button spacing for multiple link-style buttons

### ISSUE THREAD

**Issue by harrism-github** [fs-webdev/fs-styles#45]
![screen shot 2015-08-20 at 3 06 52 pm](https://cloud.githubusercontent.com/assets/1877875/9395728/55442a48-474d-11e5-958b-18f6f5b87068.png)

Notice that the spacing is not uniform.  Fixing spacing w/ css makes focus outline look bad.  How to fix?

**Comment by lambertsteven** [comment]
@swordboy1 @flpetho

**Comment by lambertsteven** [comment]
@flpetho suggests that the cancel should be placed on the right to separate the two links. The buttons are following familysearch styles, but each designer will need to determine how best to apply those styles to make them ascetically pleasing.
