### ISSUE TITLE
Print styles for person

### ISSUE THREAD

**Issue by lambertsteven** [fs-webdev/fs-styles#55]
Printing the person modules doesn't show the gender icons. For some reason, using a div with the `fs-icon` doesn't work, but using a div with `fs-icon-before` does work.

**Comment by lambertsteven** [comment]
@crowtherdr

**Comment by lambertsteven** [comment]
I just want you to know, that this fix makes me feel dirty... very dirty... Just so you know, this is why background images are turned off in print: https://github.com/twbs/bootstrap/blob/master/dist/css/bootstrap.css#L191

**Comment by crowtherdr** [comment]
Sorry abt the dirtiness :)
