### ISSUE TITLE
Print styles for person on Person page Family Members section.

### ISSUE THREAD

**Issue by crowtherdr** [fs-webdev/fs-styles#57]
When printing the Person page, the names in the Family Members section are on one line and overlapping the information to the right of the names.

see https://almtools.ldschurch.org/fhjira/browse/OFT-65075

I am adding these styles to the ng-familyMembers gadget in frontier-tree to override this.

  .family-members .fs-person-vitals__name-full,
  .family-members .fs-person-vitals__name-given,
  .family-members .fs-person-vitals__name-family,
  .family-members .fs-person-vitals__name {
    white-space: normal;
  }

**Comment by straker** [comment]
Closing unless you feel its still a problem.

**Comment by crowtherdr** [comment]
I don't see this as a problem anymore.
